Ios 626
wavesplatform/WavesWallet-iOS pull request #386
Opened 2019-07-16 12:27 UTC by xdozorx

2019-07-16 16:26 UTC, mefilt commented on DomainLayer/Sources/UseCases/OrderBookUseCase.swift
> +                        return self.assetsInteractor.assets(by: baseSettings.feeAssets.map{$0.assetId},
Разбей код на два метода

2019-07-16 16:27 UTC, mefilt commented on DomainLayer/Sources/UseCases/TransactionsUseCase.swift
> +            let assetFee = assetRate * Double(settingsOrderFee.baseFee + Int64(400000) * n)
Константа?

2019-07-16 16:28 UTC, mefilt commented on WavesWallet-iOS/Modules/TransactionCard/TransactionCardSystemTransaction+Mapper.swift
> +        var fee2: BalanceLabel.Model?
Почему ? а не !

2019-07-16 16:32 UTC, mefilt commented on DomainLayer/Sources/Mapper/TransactionDomainDTO+Mapper.swift
> +        if let matcherFeeAssetId = order1.matcherFeeAssetId {
А ты добавил matcherFeeAssetId в список загрузок asset id ?

2019-07-16 16:34 UTC, mefilt commented on DomainLayer/Sources/UseCases/Protocol/TransactionsUseCaseProtocol.swift
> +        case createOrder(amountAsset: String, priceAsset: String, settingsOrderFee: DomainLayer.DTO.Dex.SmartSettingsOrderFee, feeAssetId: String?)
Почему feeAssetId optional?

2019-07-16 16:37 UTC, mefilt commented on WavesWallet-iOS/Modules/Dex/DexCreateOrder/DexCreateOrderViewController.swift
> +        presenter.system(feedbacks: [feedback], feeAssetId: order.feeAssetId)
Ты можешь feeAssetId передать через presenter init?

2019-07-16 16:38 UTC, mefilt requested changes
Есть пару замечайний

2019-07-16 17:48 UTC, xdozorx commented on DomainLayer/Sources/UseCases/TransactionsUseCase.swift
> +            let assetFee = assetRate * Double(settingsOrderFee.baseFee + Int64(400000) * n)
лучше не надо, потому что в файле 1к кода, потом не понятно будет что за число

2019-07-16 17:48 UTC, xdozorx commented on WavesWallet-iOS/Modules/TransactionCard/TransactionCardSystemTransaction+Mapper.swift
> +        var fee2: BalanceLabel.Model?
потому что у нас вторая коммисия опциональная.

2019-07-16 17:50 UTC, xdozorx commented on DomainLayer/Sources/Mapper/TransactionDomainDTO+Mapper.swift
> +        if let matcherFeeAssetId = order1.matcherFeeAssetId {
добавил.  вот сюда TransactionsUseCase.swift ->
 private extension DomainLayer.DTO.AnyTransaction {
    var assetsIds: [String] {

   }
}

2019-07-16 17:52 UTC, xdozorx commented on DomainLayer/Sources/UseCases/Protocol/TransactionsUseCaseProtocol.swift
> +        case createOrder(amountAsset: String, priceAsset: String, settingsOrderFee: DomainLayer.DTO.Dex.SmartSettingsOrderFee, feeAssetId: String?)
поправил

2019-07-16 17:54 UTC, xdozorx commented on WavesWallet-iOS/Modules/Dex/DexCreateOrder/DexCreateOrderViewController.swift
> +        presenter.system(feedbacks: [feedback], feeAssetId: order.feeAssetId)
неа, у меня на методе инициализации презентера еще не известна коммисия

2019-07-16 22:17 UTC, mefilt commented on DomainLayer/Sources/UseCases/TransactionsUseCase.swift
> +            let assetFee = assetRate * Double(settingsOrderFee.baseFee + Int64(400000) * n)
rateSmart

2019-07-16 22:40 UTC, xdozorx commented on DomainLayer/Sources/UseCases/OrderBookUseCase.swift
> +                        return self.assetsInteractor.assets(by: baseSettings.feeAssets.map{$0.assetId},
сделал

2019-07-16 22:42 UTC, xdozorx commented on DomainLayer/Sources/UseCases/TransactionsUseCase.swift
> +            let assetFee = assetRate * Double(settingsOrderFee.baseFee + Int64(400000) * n)
сделал

2019-07-17 15:15 UTC, mefilt approved these changes

2019-07-17 15:23 UTC, merged