Ios 717
wavesplatform/WavesWallet-iOS pull request #404
Opened 2019-08-11 18:30 UTC by xdozorx

2019-08-13 11:45 UTC, mefilt commented on DataLayer/Sources/Repositories/Dex/DexPairsPriceRepositoryRemote.swift
> +        let searchCompoments = searchText.components(separatedBy: "/")
либо обратный "/"

2019-08-13 11:46 UTC, mefilt commented on DataLayer/Sources/Mapper/DexAssetPairDomainDTO+Mapper.swift
> +        let isChecked = realm.object(ofType: DexAssetPair.self, forPrimaryKey: id) != nil
Давай в будущем не использовать realm на прямую!

2019-08-13 11:49 UTC, mefilt commented on DataLayer/Sources/Repositories/Dex/DexPairsPriceRepositoryRemote.swift
> +        return environmentRepository
А если вместо имен будет assetId. Будет работать поиск?

2019-08-13 11:49 UTC, mefilt commented on DomainLayer/Sources/Models/DTO/DexDomainDTO.swift
> +    struct SimplePair {
я недавно завел такой

2019-08-13 11:52 UTC, mefilt commented on DomainLayer/Sources/Repositories/DexPairsPriceRepositoryProtocol.swift
> +    func mapPairs(by accountAddress: String, pairs: [DomainLayer.DTO.Dex.Pair]) -> Observable<[DomainLayer.DTO.Dex.SmartPair]>
Я у себя сделал поиск пар

func searchPairs(_ query: DomainLayer.Query.Dex.SearchPairs) ->Observable<DomainLayer.DTO.Dex.PairsSearch>

2019-08-13 11:52 UTC, mefilt commented on WavesWallet-iOS/Modules/Dex/DexMarket/Interactor/DexMarketInteractor.swift
> +    static let maxGeneralAssets = 4
Это что?

2019-08-13 11:53 UTC, mefilt requested changes
надо бы нам как-то договориться по общему функционалу

2019-08-13 18:04 UTC, xdozorx commented on DataLayer/Sources/Repositories/Dex/DexPairsPriceRepositoryRemote.swift
> +        let searchCompoments = searchText.components(separatedBy: "/")
сделал

2019-08-13 18:05 UTC, xdozorx commented on DataLayer/Sources/Mapper/DexAssetPairDomainDTO+Mapper.swift
> +        let isChecked = realm.object(ofType: DexAssetPair.self, forPrimaryKey: id) != nil
будет 100 моделей. если в цикле в каждой моделе вызывать Ream, мне кажеться большая нагрузка на память будет.

2019-08-13 18:06 UTC, xdozorx commented on DataLayer/Sources/Repositories/Dex/DexPairsPriceRepositoryRemote.swift
> +        return environmentRepository
ищет

2019-08-13 18:07 UTC, xdozorx commented on DomainLayer/Sources/Models/DTO/DexDomainDTO.swift
> +    struct SimplePair {
в моей ветке и develop такого нету

2019-08-13 18:09 UTC, xdozorx commented on DomainLayer/Sources/Repositories/DexPairsPriceRepositoryProtocol.swift
> +    func mapPairs(by accountAddress: String, pairs: [DomainLayer.DTO.Dex.Pair]) -> Observable<[DomainLayer.DTO.Dex.SmartPair]>
тогда как будем делать?
мне еще не нравиться что я тут сделал функцию 
func mapPairs(by accountAddress: String, pairs: [DomainLayer.DTO.Dex.Pair]) -> Observable<[DomainLayer.DTO.Dex.SmartPair]>

которая по сути обращаеться только в BD. а сделал потому что я не могу из кода в приложении обратиться к Realm, поэтому пришлось в репозитории сделать функци. можно просто надобыло только другой репозиторий...

2019-08-13 18:09 UTC, xdozorx commented on WavesWallet-iOS/Modules/Dex/DexMarket/Interactor/DexMarketInteractor.swift
> +    static let maxGeneralAssets = 4
количество первых generalAssets из которых будут формироваться пары

2019-08-13 21:00 UTC, mefilt commented on DataLayer/Sources/Repositories/Dex/DexPairsPriceRepositoryRemote.swift
> +        print(searchCompoments)
print

2019-08-13 21:01 UTC, mefilt commented on DomainLayer/Sources/Repositories/DexPairsPriceRepositoryProtocol.swift
> +    func mapPairs(by accountAddress: String, pairs: [DomainLayer.DTO.Dex.Pair]) -> Observable<[DomainLayer.DTO.Dex.SmartPair]>
Завтра обсудим

2019-08-13 21:01 UTC, mefilt requested changes
Посмотри

2019-08-14 08:05 UTC, xdozorx commented on DataLayer/Sources/Repositories/Dex/DexPairsPriceRepositoryRemote.swift
> +        print(searchCompoments)
убрал

2019-08-16 09:19 UTC, mefilt approved these changes

2019-08-16 09:19 UTC, merged