Ios 718
wavesplatform/WavesWallet-iOS pull request #405
Opened 2019-08-12 12:41 UTC by xdozorx

2019-08-13 11:30 UTC, mefilt commented on DataLayer/Sources/Repositories/Dex/MatcherRepositoryLocal.swift
> +    private var publicKeyAccount: PublicKeyAccount?
Не хватает mutex - так как могут два одновременно использовать
Не хватает share(replay: 1, scope: SubjectLifetimeScope.whileConnected) - переиспользование запроса
Примеры в EnvironmentRepository

2019-08-13 11:31 UTC, mefilt commented on DataLayer/Sources/Repositories/Dex/MatcherRepositoryLocal.swift
> +final class MatcherRepositoryLocal: MatcherRepositoryProtocol {
Давай вместо Local -> Storage. 
Будем переименовывать остальные

2019-08-13 11:31 UTC, mefilt commented on DataLayer/Sources/Repositories/Dex/MatcherRepositoryLocal.swift
> +        return matcherRepositoryRemote.matcherPublicKey(accountAddress: accountAddress)
зачем тут accountAddress?

2019-08-13 11:43 UTC, mefilt commented on DataLayer/Sources/Repositories/Dex/MatcherRepositoryLocal.swift
> +final class MatcherRepositoryLocal: MatcherRepositoryProtocol {
Я предлагаю разделить RepositoryProtocol на две сущности
1) Storage
2) Repository

Сейчас какая-та путаница с ними и не понятно кто что делает
На примере с этим будет

MatcherStorageProtocol - BD (local)
MatcherRepositoryProtocol -  Remote(API) и не только
Есть идеи?

2019-08-13 11:44 UTC, mefilt requested changes
=(

2019-08-13 13:28 UTC, xdozorx commented on DataLayer/Sources/Repositories/Dex/MatcherRepositoryLocal.swift
> +    private var publicKeyAccount: PublicKeyAccount?
сделал

2019-08-13 13:32 UTC, xdozorx commented on DataLayer/Sources/Repositories/Dex/MatcherRepositoryLocal.swift
> +        return matcherRepositoryRemote.matcherPublicKey(accountAddress: accountAddress)
потому что в matcherRepositoryRemote функция требует адрес

2019-08-13 16:14 UTC, mefilt commented on DataLayer/Sources/Repositories/Dex/MatcherRepositoryLocal.swift
> +        return matcherRepositoryRemote.matcherPublicKey(accountAddress: accountAddress)
Открой код :)

2019-08-13 17:34 UTC, xdozorx commented on DataLayer/Sources/Repositories/Dex/MatcherRepositoryLocal.swift
> +        return matcherRepositoryRemote.matcherPublicKey(accountAddress: accountAddress)
сделал

2019-08-13 20:59 UTC, mefilt requested changes
Не делай push --force
Я не вижу изминений

2019-08-13 20:59 UTC, mefilt commented on DataLayer/Sources/Repositories/Dex/MatcherRepositoryLocal.swift
> +                objc_sync_enter(self)
не правильно.

2019-08-13 20:59 UTC, mefilt commented on DataLayer/Sources/Repositories/Dex/MatcherRepositoryLocal.swift
> +        if let publicKey = publicKeyAccount {
А зачем тут?

2019-08-14 08:09 UTC, xdozorx commented on DataLayer/Sources/Repositories/Dex/MatcherRepositoryLocal.swift
> +        if let publicKey = publicKeyAccount {
убрал

2019-08-14 08:09 UTC, xdozorx commented on DataLayer/Sources/Repositories/Dex/MatcherRepositoryLocal.swift
> +                objc_sync_enter(self)
надо обсудить

2019-08-15 11:24 UTC, mefilt approved these changes
Ok

2019-08-15 11:24 UTC, merged